import torch
import torch.nn as nn
from .modules.encoder import MLPEncoder


class LSTMSeqEncoder(nn.Module):
    def __init__(self, in_size, hidden_size, dropout, num_layers=1):
        super().__init__()
        self.input_drop = nn.Dropout(dropout)
        self.rnn = nn.LSTM(in_size, hidden_size, num_layers=num_layers,
                           batch_first=True, bidirectional=False)
        self.output_drop = nn.Dropout(dropout)

    def forward(self, x):
        out, _ = self.rnn(self.input_drop(x))
        return self.output_drop(out)


class LearnableQueryPooling(nn.Module):
    """Single learnable query attends over sequence → (B, H)."""

    def __init__(self, hidden_dim, num_heads, dropout):
        super().__init__()
        self.query = nn.Parameter(torch.zeros(1, 1, hidden_dim))
        nn.init.normal_(self.query, std=0.02)
        self.attn = nn.MultiheadAttention(
            embed_dim=hidden_dim, num_heads=num_heads,
            dropout=dropout, batch_first=True,
        )

    def forward(self, x):
        q = self.query.expand(x.size(0), -1, -1)    # (B, 1, H)
        out, _ = self.attn(query=q, key=x, value=x)  # (B, 1, H)
        return out.squeeze(1)                         # (B, H)


# ── ATOMIC-derived compatibility matrix ──────────────────────────────────────
# Rows = speaker emotion, Cols = listener emotion
# Labels: 0=neutral 1=angry 2=happy 3=sad 4=worried 5=surprise
#
# SOURCE: generated by build_compat_matrix.py (COMET-ATOMIC2020, oReact)
# Replace this block with the output of build_compat_matrix.py after running it.
#
#               neu  ang  hap  sad  wor  sur
_COMPAT_DATA = [
    [1, 1, 1, 1, 1, 1],  # spk=neutral  (flexible — no strong signal)
    [1, 1, 0, 1, 1, 0],  # spk=angry    → worried/sad; not happy/surprise
    [1, 0, 1, 0, 0, 1],  # spk=happy    → happy/surprise; not angry/sad/worried
    [1, 0, 0, 1, 1, 0],  # spk=sad      → sad/worried; not happy/surprise
    [1, 0, 0, 1, 1, 0],  # spk=worried  → worried/sad; not happy/surprise
    [1, 0, 1, 0, 0, 1],  # spk=surprise → happy/surprise; not negative
]


class MemoCMTFusion(nn.Module):
    """
    Speaker branch : LSTM → bidir cross-attention (audio↔text) → mean pool
    Listener branch: LSTM → LearnableQueryPooling
    Fusion         : Q=listener, K/V=speaker cross-attention + residual

    Cross-pair augmentation (training only):
        With prob cross_pair_p, replace speaker_feat[i] with speaker_feat[j]
        where j is sampled from batch samples whose emotion is compatible with
        sample i's listener emotion, according to ATOMIC oReact causality.
        Listener feat and labels stay fixed → simulates interlocutor test condition.

    Modality dropout (training only):
        With prob speaker_drop_p, zero out entire speaker branch.
    """

    def __init__(self, args):
        super().__init__()

        audio_dim   = args.audio_dim
        text_dim    = args.text_dim
        video_dim   = args.video_dim
        output_dim1 = args.output_dim1
        output_dim2 = args.output_dim2
        dropout     = args.dropout
        hidden_dim  = args.hidden_dim
        self.grad_clip = args.grad_clip

        self.feat_type      = getattr(args, 'feat_type',      'utt')
        self.speaker_drop_p = getattr(args, 'speaker_drop_p', 0.2)
        self.cross_pair_p   = getattr(args, 'cross_pair_p',   0.5)
        self.use_curriculum = getattr(args, 'use_curriculum', True)
        self.current_epoch  = 0

        num_heads = max(1, hidden_dim // 64)

        # ── Compatibility matrix (ATOMIC-derived, not a learnable param) ───
        compat = torch.tensor(_COMPAT_DATA, dtype=torch.long)
        self.register_buffer('compat_matrix', compat)

        # ── Encoders ──────────────────────────────────────────────────────
        if self.feat_type in ['frm_align', 'frm_unalign']:
            self.audio_encoder = LSTMSeqEncoder(audio_dim, hidden_dim, dropout)
            self.text_encoder  = LSTMSeqEncoder(text_dim,  hidden_dim, dropout)
            self.video_encoder = LSTMSeqEncoder(video_dim, hidden_dim, dropout)
        else:
            self.audio_encoder = MLPEncoder(audio_dim, hidden_dim, dropout)
            self.text_encoder  = MLPEncoder(text_dim,  hidden_dim, dropout)
            self.video_encoder = MLPEncoder(video_dim, hidden_dim, dropout)

        # ── Speaker: bidirectional cross-attention ─────────────────────────
        self.cross_attn_a2t = nn.MultiheadAttention(
            embed_dim=hidden_dim, num_heads=num_heads,
            dropout=dropout, batch_first=True,
        )
        self.proj_a2t = nn.Linear(hidden_dim, hidden_dim)
        self.norm_a2t = nn.LayerNorm(hidden_dim)

        self.cross_attn_t2a = nn.MultiheadAttention(
            embed_dim=hidden_dim, num_heads=num_heads,
            dropout=dropout, batch_first=True,
        )
        self.proj_t2a = nn.Linear(hidden_dim, hidden_dim)
        self.norm_t2a = nn.LayerNorm(hidden_dim)

        self.speaker_drop = nn.Dropout(dropout)

        # ── Listener: learnable query pooling ─────────────────────────────
        self.listener_pool = LearnableQueryPooling(hidden_dim, num_heads, dropout)

        # ── Fusion ────────────────────────────────────────────────────────
        self.cross_attn_fusion = nn.MultiheadAttention(
            embed_dim=hidden_dim, num_heads=num_heads,
            dropout=dropout, batch_first=True,
        )
        self.norm_fusion = nn.LayerNorm(hidden_dim)
        self.fuse_drop   = nn.Dropout(dropout)

        # ── Classifier ────────────────────────────────────────────────────
        self.fc_out_1 = nn.Linear(hidden_dim, output_dim1)
        self.fc_out_2 = nn.Linear(hidden_dim, output_dim2)

    def _compatible_pairing(self, speaker_feat: torch.Tensor,
                             emos: torch.Tensor) -> torch.Tensor:
        """
        For each sample i (listener emotion = emos[i]), find a donor j in the
        batch where compat_matrix[emos[j], emos[i]] == 1 (j's emotion as
        speaker is causally plausible for i's listener emotion).

        Falls back to keeping speaker_feat[i] unchanged if no donor found.
        Returns new speaker_feat with swapped rows.
        """
        B = speaker_feat.size(0)
        new_feat = speaker_feat.clone()

        for i in range(B):
            # compat_matrix[emos[j], emos[i]]: is emos[j] a valid speaker
            # emotion that could cause listener emotion emos[i]?
            valid = self.compat_matrix[emos, emos[i]].bool()  # (B,)
            valid[i] = False                                    # exclude self
            donors = valid.nonzero(as_tuple=True)[0]

            if donors.numel() > 0:
                idx = torch.randint(donors.numel(), (1,), device=emos.device)
                j   = donors[idx].item()
                new_feat[i] = speaker_feat[j]
            # else: no compatible donor → keep original (no augmentation)

        return new_feat

    def forward(self, batch):
        audio = batch['audios']
        text  = batch['texts']
        video = batch['videos']

        # ── Encode ────────────────────────────────────────────────────────
        if self.feat_type in ['frm_align', 'frm_unalign']:
            h_a = self.audio_encoder(audio)   # (B, T_a, H)
            h_t = self.text_encoder(text)     # (B, T_t, H)
            h_v = self.video_encoder(video)   # (B, T_v, H)
        else:
            h_a = self.audio_encoder(audio).unsqueeze(1)  # (B, 1, H)
            h_t = self.text_encoder(text).unsqueeze(1)    # (B, 1, H)
            h_v = self.video_encoder(video).unsqueeze(1)  # (B, 1, H)

        # ── Speaker: bidir cross-attention → mean pool ────────────────────
        a2t, _ = self.cross_attn_a2t(query=h_a, key=h_t, value=h_t)
        a2t     = self.norm_a2t(self.proj_a2t(a2t))           # (B, T_a, H)

        t2a, _ = self.cross_attn_t2a(query=h_t, key=h_a, value=h_a)
        t2a     = self.norm_t2a(self.proj_t2a(t2a))           # (B, T_t, H)

        speaker_seq  = torch.cat([a2t, t2a], dim=1)           # (B, T_a+T_t, H)
        speaker_feat = self.speaker_drop(speaker_seq.mean(dim=1))  # (B, H)

        # ── ATOMIC-guided cross-pair augmentation (training only) ──────────
        if self.use_curriculum:
            ep = self.current_epoch
            if ep <= 20:
                p = 0.2 * ep / 20                          # 0.0 → 0.2
            elif ep <= 60:
                p = 0.2 + 0.3 * (ep - 20) / 40            # 0.2 → 0.5
            else:
                p = 0.5
        else:
            p = self.cross_pair_p
        if self.training and torch.rand(1).item() < p:
            speaker_feat = self._compatible_pairing(speaker_feat, batch['emos'])

        # ── Modality dropout (training only) ──────────────────────────────
        if self.training and torch.rand(1).item() < self.speaker_drop_p:
            speaker_feat = torch.zeros_like(speaker_feat)

        # ── Listener: learnable query pooling ─────────────────────────────
        listener_feat = self.listener_pool(h_v)                # (B, H)

        # ── Fusion: Q=listener, K/V=speaker + residual ────────────────────
        q  = listener_feat.unsqueeze(1)   # (B, 1, H)
        kv = speaker_feat.unsqueeze(1)    # (B, 1, H)
        attn_out, _ = self.cross_attn_fusion(query=q, key=kv, value=kv)
        features = self.fuse_drop(
            self.norm_fusion(attn_out.squeeze(1) + listener_feat)
        )                                                       # (B, H)

        emos_out  = self.fc_out_1(features)
        vals_out  = self.fc_out_2(features)
        interloss = torch.zeros(1, device=audio.device).squeeze()

        return features, emos_out, vals_out, interloss
